<?php
// Prevent execution timeouts
set_time_limit(60);

// Configuration
$spreadsheetId   = '1wikg9wLBdXCMxZZBC3adIluOarrSpZiG8xg_EUP-eqY';
// Metrics block (name/unit/average/factor/info/carbon) + total block, queried in a single batch request
$metricsRange    = 'Carbon!A2:P7';
$totalRange      = 'Carbon!A12:B12';
$jsonKeyFilePath = __DIR__ . '/human-algorithm-cron-d2896ed90701.json';

// ==========================================
// 1. Authenticate Service Account via Pure PHP JWT
// ==========================================

if (!file_exists($jsonKeyFilePath)) {
    die("Error: json auth file missing (the one generated by Google Cloud service).");
}

$keyData     = json_decode(file_get_contents($jsonKeyFilePath), true);
$privateKey  = $keyData['private_key'];
$clientEmail = $keyData['client_email'];

// Helper function to Base64Url encode required for JWT (with safety check)
if (!function_exists('base64UrlEncode')) {
    function base64UrlEncode($data) {
        return str_replace(['+', '/', '='], ['-', '_', ''], base64_encode($data));
    }
}

// Build the JWT Header & Payload
$header = json_encode(['alg' => 'RS256', 'typ' => 'JWT']);
$now    = time();
$payload = json_encode([
    'iss'   => $clientEmail,
    'scope' => 'https://www.googleapis.com/auth/spreadsheets.readonly',
    'aud'   => 'https://oauth2.googleapis.com/token',
    'exp'   => $now + 3600,
    'iat'   => $now
]);

$base64UrlHeader    = base64UrlEncode($header);
$base64UrlPayload   = base64UrlEncode($payload);
$signatureInput     = $base64UrlHeader . "." . $base64UrlPayload;

// Sign the JWT utilizing the OpenSSL extension
if (!openssl_sign($signatureInput, $signature, $privateKey, OPENSSL_ALGO_SHA256)) {
    die("Error: Failed to sign the JWT via OpenSSL.");
}
$base64UrlSignature = base64UrlEncode($signature);
$jwt                = $signatureInput . "." . $base64UrlSignature;

// Exchange the JWT for an ephemeral OAuth2 Access Token
$tokenUrl   = 'https://oauth2.googleapis.com/token';
$postFields = 'grant_type=' . urlencode('urn:ietf:params:oauth:grant-type:jwt-bearer') . '&assertion=' . urlencode($jwt);

$ch = curl_init($tokenUrl);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, $postFields);
$tokenResponse = curl_exec($ch);
curl_close($ch);

$tokenData = json_decode($tokenResponse, true);
if (!isset($tokenData['access_token'])) {
    die("Error: OAuth2 token exchange failed. Verify Google Cloud Service Account permissions.");
}
$accessToken = $tokenData['access_token'];

// ==========================================
// 2. Fetch metrics + total ranges in a single batchGet request
// ==========================================

$apiUrl = "https://sheets.googleapis.com/v4/spreadsheets/{$spreadsheetId}/values:batchGet"
    . "?ranges=" . urlencode($metricsRange)
    . "&ranges=" . urlencode($totalRange);

$ch = curl_init($apiUrl);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_TIMEOUT, 10);
curl_setopt($ch, CURLOPT_HTTPHEADER, [
    "Authorization: Bearer {$accessToken}",
    "Accept: application/json"
]);
$response = curl_exec($ch);
curl_close($ch);

if (!$response) {
    die("Error: Incapable of reaching the Google API via cURL.");
}

$payloadData = json_decode($response, true);
if (!isset($payloadData['valueRanges'][0]['values']) || !isset($payloadData['valueRanges'][1]['values'])) {
    die("Error: Invalid payload data matrix received from Google Sheets.");
}

$metricsRows = $payloadData['valueRanges'][0]['values']; // Rows 2-7 (Metrics, Unit, Weekly average, Factor, Factor info, Weekly carbon)
$totalRow    = $payloadData['valueRanges'][1]['values'][0] ?? []; // Row 12 (TOTAL WEEKLY CARBON, value)

// Defensive validation check to ensure payload layout matches expectations
if (count($metricsRows) < 6) {
    die("Error: Spreadsheet data layout is truncated or incomplete.");
}

/**
 * Spatial mapping of the metrics block (columns B to P, one column per metric):
 * row 0 -> Metrics (names)
 * row 1 -> Unit
 * row 2 -> Weekly average
 * row 3 -> Factor to kg eqCO2
 * row 4 -> Factor information
 * row 5 -> Weekly carbon
 *
 * Column B..P maps to these stable metric ids/names, in spreadsheet order.
 */
$metricIds = [
    'energy', 'wifi', '5g', 'cold-water', 'hot-water', 'gasoline', 'kerosene',
    'train-travels', 'ai-engine-prompts', 'ai-copilot-prompts', 'ai-copilot-credits',
    'ai-gemini-prompts', 'produced-software', 'cloud-data', 'local-data'
];

$names      = array_slice($metricsRows[0], 1);
$units      = array_slice($metricsRows[1], 1);
$averages   = array_slice($metricsRows[2], 1);
$factors    = array_slice($metricsRows[3], 1);
$factorInfo = array_slice($metricsRows[4], 1);
$carbons    = array_slice($metricsRows[5], 1);

$metrics = [];
foreach ($metricIds as $index => $id) {
    $metrics[] = [
        "id"                => $id,
        "name"              => isset($names[$index])    ? htmlspecialchars(trim($names[$index]), ENT_QUOTES, 'UTF-8')    : "",
        "unit"              => isset($units[$index])     ? htmlspecialchars(trim($units[$index]), ENT_QUOTES, 'UTF-8')     : "",
        "weekly_average"    => isset($averages[$index])  ? (float)$averages[$index]  : 0.0,
        "factor_to_kg_co2"  => isset($factors[$index])    ? (float)$factors[$index]    : 0.0,
        "factor_info"       => isset($factorInfo[$index]) ? htmlspecialchars(trim($factorInfo[$index]), ENT_QUOTES, 'UTF-8') : "",
        "weekly_carbon_kg"  => isset($carbons[$index])    ? (float)$carbons[$index]    : 0.0
    ];
}

// ==========================================
// 3. Construct and save structured JSON payload
// ==========================================

$dataPath = __DIR__ . '/../website/data/carbon-metrics-latest-data.json';

$jsonStructure = [
    "total_weekly_carbon_kg" => isset($totalRow[1]) ? (float)$totalRow[1] : 0.0,
    "last_updated"           => date('Y-m-d'),
    "metrics"                => $metrics
];

// Encode structure into pretty-printed JSON format
$jsonContent = json_encode($jsonStructure, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);

if ($jsonContent === false) {
    die("Error: Failed to serialize matrix data array into structured JSON.");
}

// Write the compiled JSON structure safely to disk
if (file_put_contents($dataPath, $jsonContent) !== false) {
    echo "Success: External carbon-metrics-latest-data.json file generated dynamically.";
} else {
    echo "Error: Failed to write carbon-metrics-latest-data.json file to disk.";
}
