<?php
// Prevent execution timeouts
set_time_limit(60);

// Configuration
$spreadsheetId   = '1iubFtCGyafCtQ4yCyCLbPjxBJNzMK8I2lktiE_tkdGw';
// Query the entire bounding range in one request to maximize network performance
$range           = 'Metrics!A4:A31'; 
$jsonKeyFilePath = __DIR__ . '/human-algorithm-cron-d2896ed90701.json';

// ==========================================
// 1. Authenticate Service Account via Pure PHP JWT
// ==========================================

if (!file_exists($jsonKeyFilePath)) {
    die("Error: json auth file missing (the one generated by Google Cloud service).");
}

$keyData     = json_decode(file_get_contents($jsonKeyFilePath), true);
$privateKey  = $keyData['private_key'];
$clientEmail = $keyData['client_email'];

// Helper function to Base64Url encode required for JWT (with safety check)
if (!function_exists('base64UrlEncode')) {
    function base64UrlEncode($data) {
        return str_replace(['+', '/', '='], ['-', '_', ''], base64_encode($data));
    }
}

// Build the JWT Header & Payload
$header = json_encode(['alg' => 'RS256', 'typ' => 'JWT']);
$now    = time();
$payload = json_encode([
    'iss'   => $clientEmail,
    'scope' => 'https://www.googleapis.com/auth/spreadsheets.readonly',
    'aud'   => 'https://oauth2.googleapis.com/token',
    'exp'   => $now + 3600,
    'iat'   => $now
]);

$base64UrlHeader    = base64UrlEncode($header);
$base64UrlPayload   = base64UrlEncode($payload);
$signatureInput     = $base64UrlHeader . "." . $base64UrlPayload;

// Sign the JWT utilizing the OpenSSL extension
if (!openssl_sign($signatureInput, $signature, $privateKey, OPENSSL_ALGO_SHA256)) {
    die("Error: Failed to sign the JWT via OpenSSL.");
}
$base64UrlSignature = base64UrlEncode($signature);
$jwt                = $signatureInput . "." . $base64UrlSignature;

// Exchange the JWT for an ephemeral OAuth2 Access Token
$tokenUrl   = 'https://oauth2.googleapis.com/token';
$postFields = 'grant_type=' . urlencode('urn:ietf:params:oauth:grant-type:jwt-bearer') . '&assertion=' . urlencode($jwt);

$ch = curl_init($tokenUrl);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, $postFields);
$tokenResponse = curl_exec($ch);
curl_close($ch);

$tokenData = json_decode($tokenResponse, true);
if (!isset($tokenData['access_token'])) {
    die("Error: OAuth2 token exchange failed. Verify Google Cloud Service Account permissions.");
}
$accessToken = $tokenData['access_token'];

// ==========================================
// 2. Fetch bulk data range from Google Sheets API
// ==========================================

$apiUrl = "https://sheets.googleapis.com/v4/spreadsheets/{$spreadsheetId}/values/" . urlencode($range);

$ch = curl_init($apiUrl);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_TIMEOUT, 10);
curl_setopt($ch, CURLOPT_HTTPHEADER, [
    "Authorization: Bearer {$accessToken}",
    "Accept: application/json"
]);
$response = curl_exec($ch);
curl_close($ch);

if (!$response) {
    die("Error: Incapable of reaching the Google API via cURL.");
}

$payloadData = json_decode($response, true);
if (!isset($payloadData['values']) || !is_array($payloadData['values'])) {
    die("Error: Invalid payload data matrix received from Google Sheets.");
}

// Flat-map the vertical array rows into a predictable index array
$rows = [];
foreach ($payloadData['values'] as $row) {
    $rows[] = isset($row[0]) ? trim($row[0]) : '';
}

/**
 * Spatial mapping based on the exact index sequence (A4 to A31):
 * index 0  (A4)  -> LAST ENTRY NUMBER
 * index 3  (A7)  -> LAST ENTRY EXEC TIME
 * index 6  (A10) -> LAST ENTRY SUCCESS STATE
 * index 9  (A13) -> LAST ENTRY DATE
 * index 12 (A16) -> LONGEST SUCCESS NUMBER
 * index 15 (A19) -> LONGEST SUCCESS EXEC TIME
 * index 18 (A22) -> LONGEST SUCCESS DATE
 * index 21 (A25) -> SUCCESS RATIO
 * index 24 (A28) -> TOTAL DATA PROCESSED
 * index 27 (A31) -> TOTAL COMPUTATION TIME
 */

// Defensive validation check to ensure payload length matches expectations
if (count($rows) < 28) {
    die("Error: Spreadsheet data layout is truncated or incomplete.");
}

// Map variables dynamically with type-casting and sanitation
$lastSuccessState = (strcasecmp($rows[6], 'Yes') === 0 || strcasecmp($rows[6], 'true') === 0);

// ==========================================
// 3. Construct and save structured JSON payload
// ==========================================

$dataPath = __DIR__ . '/../website/data/human-algorithm-latest-data.json';

$jsonStructure = [
    "last_entry" => [
        "number"                 => isset($rows[0])  ? (int)$rows[0] : 0,
        "execution_time_seconds" => isset($rows[3])  ? (int)$rows[3] : 0,
        "success"                => $lastSuccessState,
        "date"                   => isset($rows[9])  ? htmlspecialchars($rows[9], ENT_QUOTES, 'UTF-8') : ""
    ],
    "longest_success" => [
        "number"                 => isset($rows[12]) ? (int)$rows[12] : 0,
        "execution_time_seconds" => isset($rows[15]) ? (int)$rows[15] : 0,
        "date"                   => isset($rows[18]) ? htmlspecialchars($rows[18], ENT_QUOTES, 'UTF-8') : ""
    ],
    "aggregates" => [
        "success_ratio"                  => isset($rows[21]) ? (float)$rows[21] : 0.0,
        "total_data_processed"           => isset($rows[24]) ? (int)$rows[24] : 0,
        "total_computation_time_seconds" => isset($rows[27]) ? (int)$rows[27] : 0
    ]
];

// Encode structure into pretty-printed JSON format
$jsonContent = json_encode($jsonStructure, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);

if ($jsonContent === false) {
    die("Error: Failed to serialize matrix data array into structured JSON.");
}

// Write the compiled JSON structure safely to disk
if (file_put_contents($dataPath, $jsonContent) !== false) {
    echo "Success: External data.json file generated dynamically.";
} else {
    echo "Error: Failed to write data.json file to disk.";
}