var AboutComponent = {
    template: document.querySelector('#about-template'),
    data: function () {
        return { }
    },
    methods: {
        // Icon & color category for each metric id, matching the static sobriety section's scheme
        carbonMetricMeta: {
            'energy':               { icon: 'fa-bolt',   category: 'consumption' },
            'wifi':                 { icon: 'fa-wifi',   category: 'data' },
            '5g':                   { icon: 'fa-signal', category: 'data' },
            'cold-water':           { icon: 'fa-glass',  category: 'liquid' },
            'hot-water':            { icon: 'fa-glass',  category: 'liquid' },
            'gasoline':             { icon: 'fa-car',    category: 'liquid' },
            'kerosene':             { icon: 'fa-plane',  category: 'liquid' },
            'train-travels':        { icon: 'fa-train',  category: 'liquid' },
            'ai-engine-prompts':    { icon: 'fa-cube',   category: 'ai' },
            'ai-copilot-prompts':   { icon: 'fa-cube',   category: 'ai' },
            'ai-copilot-credits':   { icon: 'fa-cube',   category: 'ai' },
            'ai-gemini-prompts':    { icon: 'fa-cube',   category: 'ai' },
            'produced-software':    { icon: 'fa-github', category: 'data' },
            'cloud-data':           { icon: 'fa-cloud',  category: 'data' },
            'local-data':           { icon: 'fa-database', category: 'data' }
        },
        // Some metrics are stored in a smaller unit than what makes sense to display
        carbonMetricUnitOverride: {
            'energy':      { divideBy: 1000, unit: 'kWh' },
            'local-data':  { divideBy: 1000, unit: 'TB' }
        },
        formatCarbonMetricValue: function (metric) {
            let value = metric.weekly_average
            let unit = metric.unit

            let override = this.carbonMetricUnitOverride[metric.id]
            if (override) {
                value = value / override.divideBy
                unit = override.unit
            }

            return `${this.toSignificantFigures(value)} ${unit}`
        },
        // Keep 3 significant digits, trailing zeros included (e.g. "1.40", "35.0")
        toSignificantFigures: function (value) {
            return Number(value).toPrecision(3)
        },
        fetchCarbonMetrics: function () {
            // Path to the JSON file generated by the PHP cron task
            const dataUrl = './data/carbon-metrics-latest-data.json'

            fetch(dataUrl)
                .then(response => {
                    if (!response.ok) {
                        throw new Error("Network configuration issue or file missing.")
                    }
                    return response.json()
                })
                .then(data => {
                    if (typeof data.total_weekly_carbon_kg === 'number') {
                        safelySetText("#carbon-total-value", data.total_weekly_carbon_kg.toFixed(2))
                    }
                    if (data.last_updated) {
                        safelySetText("#carbon-last-update", "Last update: " + formatVerboseDate(data.last_updated))
                    }
                    if (Array.isArray(data.metrics)) {
                        this.renderCarbonMetrics(data.metrics)
                    }
                })
                .catch(error => {
                    console.error("Failed to render dynamic carbon metrics:", error)

                    safelySetText("#carbon-total-value", "--")
                    safelySetText("#carbon-last-update", "Last update: --")
                })
        },
        renderCarbonMetrics: function (metrics) {
            let grid = document.querySelector("#carbon-metrics-grid")
            if (!grid) return

            grid.innerHTML = ""

            metrics.forEach(metric => {
                let meta = this.carbonMetricMeta[metric.id] || { icon: 'fa-circle', category: 'data' }

                let item = document.createElement("div")
                item.className = "carbon-metric-item category-" + meta.category
                item.setAttribute("data-metric-id", metric.id)

                item.innerHTML = `
                    <span class="fa ${meta.icon} carbon-metric-icon"></span>
                    <span class="carbon-metric-name">${metric.name}</span>
                    <span class="carbon-metric-value">${this.formatCarbonMetricValue(metric)}</span>
                    <div class="carbon-metric-tooltip">
                        <p>Factor: ${this.toSignificantFigures(metric.factor_to_kg_co2)} kg eqCO2 / ${metric.unit}</p>
                        <p>Source: ${metric.factor_info}</p>
                        <p>Weekly carbon: ${this.toSignificantFigures(metric.weekly_carbon_kg)} kg eqCO2</p>
                    </div>
                `

                grid.appendChild(item)
            })
        },
        activateBioQuanticGlitch: function () {
            // Prepare empty arrays with texts
            let paragraphs = document.querySelectorAll(".statement-core p")
            let htmlContents = [] // Initial markup (including <em>s and such)
            let textContents = [] // Raw initial text
            let textArrays = [] // Splitted initial text
            let newArrays = [] // Shuffled text

            // Fill with text
            paragraphs.forEach((el) => {
                let htmlContent = el.innerHTML
                let textContent = el.innerText
                let textArray = textContent.split(' ')
                let newArray = textArray.slice(0) // Just clones

                htmlContents.push(htmlContent)
                textContents.push(textContent)
                textArrays.push(textArray)
                newArrays.push(newArray)
            })

            // Listeners
            paragraphs.forEach((el, i) => {
                el.addEventListener('mousemove', () => {
                    let newArray = newArrays[i]

                    // Shuffle 2 words in new array
                    let len = newArray.length
                    let randomIndex1 = Math.floor(len * Math.random())
                    let randomIndex2 = Math.floor(len * Math.random())
                    let buffer = newArray[randomIndex1]
                    newArray[randomIndex1] = newArray[randomIndex2]
                    newArray[randomIndex2] = buffer

                    // Build word outta array and print out
                    let newText = ""
                    for (let j = 0; j < len; j++) {
                        let rand = Math.random() < 0.1
                        if (rand) newText += "<em>"
                        newText += newArray[j] + " "
                        if (rand) newText += "</em>"
                    }
                    el.innerHTML = newText
                })
                el.addEventListener('mouseout', () => {
                    // Reset text
                    el.innerHTML = htmlContents[i]

                    // Start shuffling anew on each hoverin
                    newArrays[i] = textArrays[i].slice(0)
                })
            })
        },
        randomizeFrameOrientation: function () {
            if (Math.random() < 0.5) {
                document.querySelector("img#tilted-square-frame").classList += "tilt-even-more"
            }
        }
    },
    mounted: function () {

        this.activateBioQuanticGlitch()
        this.randomizeFrameOrientation()
        this.fetchCarbonMetrics()
    }
}
