// This components gathers several previous or new components
var MoreComponent = {
    template: document.querySelector("#more-template"),
    data: function () {
        return { }
    },
    methods: {
        formatVerboseDate: function (dateString) {
            if (!dateString) return ""
            
            // Split the YYYY-MM-DD string to avoid timezone/DST shifting issues
            var parts = dateString.split('-')
            if (parts.length !== 3) return dateString // Fallback if format is unexpected
            
            var year = parts[0]
            // JavaScript months are 0-indexed (January is 0, December is 11)
            var monthIndex = parseInt(parts[1], 10) - 1
            var day = parseInt(parts[2], 10)

            // Define short month array names
            var shortMonths = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
            var monthName = shortMonths[monthIndex] || ""

            // Determine the mathematical ordinal suffix (st, nd, rd, th)
            var suffix = "th"
            if (day < 11 || day > 13) {
                switch (day % 10) {
                    case 1: suffix = "st"; break
                    case 2: suffix = "nd"; break
                    case 3: suffix = "rd"; break
                }
            }

            // Reconstruct into the desired typographical layout
            return monthName + " " + day + suffix + ", " + year
        },
        formatDuration: function (totalSeconds) {
            if (totalSeconds === undefined || totalSeconds === null || isNaN(totalSeconds)) {
                return "--"
            }

            var hours = Math.floor(totalSeconds / 3600)
            var minutes = Math.floor((totalSeconds % 3600) / 60)
            var seconds = totalSeconds % 60

            // Condition A: Duration is strictly below 10 minutes (600 seconds)
            if (totalSeconds < 600) {
                // Output format: M' SS" (with seconds padded, single-digit minutes unpadded)
                var paddedSeconds = seconds < 10 ? "0" + seconds : seconds
                return minutes + "' " + paddedSeconds + '"'
            }

            // Condition B: Duration is 10 minutes or greater
            // Pad both minutes and seconds to ensure uniform double-digit structural layout
            var paddedMinutes = minutes < 10 ? "0" + minutes : minutes
            var paddedSeconds = seconds < 10 ? "0" + seconds : seconds

            if (hours > 0) {
                // Output format: Hh MM' SS"
                return hours + "h " + paddedMinutes + "' " + paddedSeconds + '"'
            } else {
                // Output format: MM' SS"
                return paddedMinutes + "' " + paddedSeconds + '"'
            }
        },
        fetchMetricsData: function () {
            // Path to the JSON file generated by your PHP cron task
            const dataUrl = './data/human-algorithm-latest-data.json'

            fetch(dataUrl)
                .then(response => {
                    if (!response.ok) {
                        throw new Error("Network configuration issue or file missing.")
                    }
                    return response.json()
                })
                .then(data => {
                    // 1. Map Last Entry Data Group
                    if (data.last_entry) {
                        this.safelySetText("#decomp-number", data.last_entry.number)
                        this.safelySetText("#decomp-time", this.formatDuration(data.last_entry.execution_time_seconds))
                        this.safelySetText("#decomp-status", data.last_entry.success ? "success" : "failed")
                        this.safelySetText("#decomp-date", this.formatVerboseDate(data.last_entry.date))
                    }

                    // 2. Map Longest Success Data Group
                    if (data.longest_success) {
                        this.safelySetText("#longest-decomp-number", data.longest_success.number)
                        this.safelySetText("#longest-decomp-time", this.formatDuration(data.longest_success.execution_time_seconds))
                        this.safelySetText("#longest-decomp-date", this.formatVerboseDate(data.longest_success.date))
                    }

                    // 3. Map Aggregates Data Group
                    if (data.aggregates) {
                        // Formats decimal ratio (e.g., 0.9318) cleanly to a localized percentage (e.g., 93.18%)
                        const formattedRatio = (data.aggregates.success_ratio * 100).toFixed(2) + " %"
                        this.safelySetText("#decomp-ratio", formattedRatio)
                        
                        // Formats plain numbers to use localized thousands separators (e.g., 192536 to 192 536)
                        this.safelySetText("#decomp-total", data.aggregates.total_data_processed.toLocaleString('en-US').replace(/,/g, ' '));
                        this.safelySetText("#computime-total", this.formatDuration(data.aggregates.total_computation_time_seconds))
                    }
                })
                .catch(error => {
                    console.error("Failed to render dynamic computational metrics:", error)

                    // Graceful fallback display values across target nodes
                    const targets = [
                        "#decomp-number", "#decomp-time", "#decomp-status", "#decomp-date",
                        "#longest-decomp-number", "#longest-decomp-time", "#longest-decomp-date",
                        "#decomp-ratio", "#decomp-total", "#computime-total"
                    ];
                    targets.forEach(selector => this.safelySetText(selector, "--"))
                });
        },
        // Defensive helper function to ensure no error is thrown if a DOM element is missing
        safelySetText: function (selector, value) {
            var element = document.querySelector(selector)
            if (element) {
                element.textContent = value
            }
        }
    },
    mounted: function () {
        // Trigger the asynchronous metric acquisition phase immediately upon component mounting
        this.fetchMetricsData()

        // Web-Dataviz Show mores
        document.querySelector(".student-misc-projects").classList.add('hidden')
        document.querySelector(".load-hum-projects").classList.add('hidden')
        document.querySelector(".hum-projects").classList.add('hidden')

        document.querySelector(".load-student-misc-projects").addEventListener('click', (ev) => {
            document.querySelector(".load-student-misc-projects").classList.add('hidden')
            document.querySelector(".student-misc-projects").classList.remove('hidden')
            document.querySelector(".load-hum-projects").classList.remove('hidden')
        })
        document.querySelector(".load-hum-projects").addEventListener('click', (ev) => {
            document.querySelector(".load-hum-projects").classList.add('hidden')
            document.querySelector(".hum-projects").classList.remove('hidden')
        })

        // Zoomable images
        document.querySelectorAll("#more img:not(.non-zoomable)").forEach(el => {
            el.addEventListener("click", (ev) => {
                let elt = ev.target
                elt.classList.toggle("clicked")
                
                if (elt.classList.contains("clicked")) updateImageZoomOrigin(elt)
            })
        })
    }
}