// This components gathers several previous or new components
var MoreComponent = {
    template: document.querySelector("#more-template"),
    data: function () {
        return { }
    },
    methods: {
        formatDuration: function (totalSeconds) {
            if (totalSeconds === undefined || totalSeconds === null || isNaN(totalSeconds)) {
                return "--"
            }

            var hours = Math.floor(totalSeconds / 3600)
            var minutes = Math.floor((totalSeconds % 3600) / 60)
            var seconds = totalSeconds % 60

            // Condition A: Duration is strictly below 10 minutes (600 seconds)
            if (totalSeconds < 600) {
                // Output format: M' SS" (with seconds padded, single-digit minutes unpadded)
                var paddedSeconds = seconds < 10 ? "0" + seconds : seconds
                return minutes + "' " + paddedSeconds + '"'
            }

            // Condition B: Duration is 10 minutes or greater
            // Pad both minutes and seconds to ensure uniform double-digit structural layout
            var paddedMinutes = minutes < 10 ? "0" + minutes : minutes
            var paddedSeconds = seconds < 10 ? "0" + seconds : seconds

            if (hours > 0) {
                // Output format: Hh MM' SS"
                return hours + "h " + paddedMinutes + "' " + paddedSeconds + '"'
            } else {
                // Output format: MM' SS"
                return paddedMinutes + "' " + paddedSeconds + '"'
            }
        },
        fetchMetricsData: function () {
            // Path to the JSON file generated by your PHP cron task
            const dataUrl = './data/human-algorithm-latest-data.json'

            fetch(dataUrl)
                .then(response => {
                    if (!response.ok) {
                        throw new Error("Network configuration issue or file missing.")
                    }
                    return response.json()
                })
                .then(data => {
                    // 1. Map Last Entry Data Group
                    if (data.last_entry) {
                        safelySetText("#decomp-number", data.last_entry.number)
                        safelySetText("#decomp-time", this.formatDuration(data.last_entry.execution_time_seconds))
                        safelySetText("#decomp-status", data.last_entry.success ? "success" : "failed")
                        safelySetText("#decomp-date", formatVerboseDate(data.last_entry.date))
                    }

                    // 2. Map Longest Success Data Group
                    if (data.longest_success) {
                        safelySetText("#longest-decomp-number", data.longest_success.number)
                        safelySetText("#longest-decomp-time", this.formatDuration(data.longest_success.execution_time_seconds))
                        safelySetText("#longest-decomp-date", formatVerboseDate(data.longest_success.date))
                    }

                    // 3. Map Aggregates Data Group
                    if (data.aggregates) {
                        // Formats decimal ratio (e.g., 0.9318) cleanly to a localized percentage (e.g., 93.18%)
                        const formattedRatio = (data.aggregates.success_ratio * 100).toFixed(2) + " %"
                        safelySetText("#decomp-ratio", formattedRatio)
                        
                        // Formats plain numbers to use localized thousands separators (e.g., 192536 to 192 536)
                        safelySetText("#decomp-total", data.aggregates.total_data_processed.toLocaleString('en-US').replace(/,/g, ' '));
                        safelySetText("#computime-total", this.formatDuration(data.aggregates.total_computation_time_seconds))
                    }
                })
                .catch(error => {
                    console.error("Failed to render dynamic computational metrics:", error)

                    // Graceful fallback display values across target nodes
                    const targets = [
                        "#decomp-number", "#decomp-time", "#decomp-status", "#decomp-date",
                        "#longest-decomp-number", "#longest-decomp-time", "#longest-decomp-date",
                        "#decomp-ratio", "#decomp-total", "#computime-total"
                    ];
                    targets.forEach(selector => safelySetText(selector, "--"))
                });
        }
    },
    mounted: function () {
        // Trigger the asynchronous metric acquisition phase immediately upon component mounting
        this.fetchMetricsData()

        // Web-Dataviz Show mores
        document.querySelector(".student-misc-projects").classList.add('hidden')
        document.querySelector(".load-hum-projects").classList.add('hidden')
        document.querySelector(".hum-projects").classList.add('hidden')

        document.querySelector(".load-student-misc-projects").addEventListener('click', (ev) => {
            document.querySelector(".load-student-misc-projects").classList.add('hidden')
            document.querySelector(".student-misc-projects").classList.remove('hidden')
            document.querySelector(".load-hum-projects").classList.remove('hidden')
        })
        document.querySelector(".load-hum-projects").addEventListener('click', (ev) => {
            document.querySelector(".load-hum-projects").classList.add('hidden')
            document.querySelector(".hum-projects").classList.remove('hidden')
        })

        // Zoomable images
        document.querySelectorAll("#more img:not(.non-zoomable)").forEach(el => {
            el.addEventListener("click", (ev) => {
                let elt = ev.target
                elt.classList.toggle("clicked")
                
                if (elt.classList.contains("clicked")) updateImageZoomOrigin(elt)
            })
        })
    }
}